apiVersion: v1
kind: BuildConfig
metadata:
  name: gsi-enablement-one.inventory-management-ui-ab
  labels:
    app: inventory-management-ui-ab
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/gsi-enablement-one/inventory-management-ui-ab.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: dev-ab
        - name: BRANCH
          value: master
